# Site
name: "IU Bloomington History Harvest"
title: "IU Bloomington History Harvest"
description: "Every day, we make history. It’s in what we eat, what we say, what we post to social media. It’s also in our homes, our backpacks and our classrooms.

<p>Each person in our Spring 2019 first-year-research course  started the semester with an object that’s important to us. Now we want to know what object you have that’s significant to you. The things here are our Hoosier history.

<p><em><a href=https://docs.google.com/forms/d/e/1FAIpQLScnAh6QqC09MJleFKIM7MMxayxLX2HFWQAoQvzNXnpdD8vU4w/viewform?usp=sf_link>Contribute to the History Harvest!</a>"
meta_description: "A200 ASURE IUB History Harvest"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  kalani:
    name: Kalani
    display_name: Kalani Craig
    image: https://history.indiana.edu/images/Faculty/craig_kalani.jpg
    email: kalani@kalanicraig.com
    web: http://www.kalanicraig.com
    twitter: https://twitter.com/kalanicraig
    description: Professor

  heather:
    name: Heather
    display_name: Heather
    image: 
    email: 
    web: 
    twitter: 
    description: Heather

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

collections:
  items:
    output: true
    permalink: /:collection/:path/
    itemid: true
    itemlabel: true
    contributor: true