# Site
name: "IU Bloomington History Harvest"
title: "IU Bloomington History Harvest"
description: "Every day, we make history. It’s in what we eat, what we say, what we post to social media. It’s also in our homes, our backpacks and our classrooms.

<p>Each person in our Spring 2019 first-year-research course  started the semester with an object that’s important to us. Now we want to know what object you have that’s significant to you. The things here are our Hoosier history.

<p><em><a href=https://docs.google.com/forms/d/e/1FAIpQLScnAh6QqC09MJleFKIM7MMxayxLX2HFWQAoQvzNXnpdD8vU4w/viewform?usp=sf_link>Contribute to the History Harvest!</a>"
meta_description: "A200 ASURE IUB History Harvest"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  ben:
    name: Ben
    display_name: Ben Dance
    image: ben.jpg
    email: 
    web: 
    twitter: 
    instagram: 
    description: 
  brian:
    name: Brian
    display_name: Brian Robusto
    image: brian.jpg
    email: 
    web: 
    twitter: 
    instagram: 
    description: 
  chelsea:
    name: Chelsea
    display_name: Chelsea Villatoro
    image: chelsea.jpg
    email: 
    web: 
    twitter: 
    instagram: 
    description: 
  heather:
    name: Heather
    display_name: Heather Hoffmeyer
    image: heather.jpg
    email: 
    web: 
    twitter: 
    instagram: 
    description: 
  jonathan:
    name: Jonathan
    display_name: Jonathan Hosey
    image: jonathan.jpg
    email: 
    web: 
    twitter: 
    instagram: 
    description: 
  kalani:
    name: Kalani
    display_name: Kalani Craig
    image: kalani.jpg
    email: kalani@kalanicraig.com
    web: http://www.kalanicraig.com
    twitter: kalanicraig
    instagram: kalanicraig
    description: Clinical Assistant Professor of History & Co-director of Institute for Digital Arts & Humanities, Indiana University Bloomington. Nerd of many types.
  kasey:
    name: Kasey
    display_name: Kasey Konz
    image: kasey.jpg
    email: 
    web: 
    twitter: 
    instagram: 
    description: 
  katie:
    name: Katie
    display_name: Katie Jamison
    image: katie.jpg
    email: 
    web: 
    twitter: 
    instagram: 
    description: 
  michael:
    name: Michael
    display_name: Michael Tetzloff
    image: michael.jpg
    email: 
    web: 
    twitter: 
    instagram: 
    description: 
  sarah:
    name: Sarah
    display_name: Sarah Gray
    image: sarah.jpg
    email: 
    web: 
    twitter: 
    instagram: 
    description: 
  skyler:
    name: Skyler
    display_name: Skyler Zenisek
    image: skyler.jpg
    email: 
    web: 
    twitter: 
    instagram: 
    description: 
  sydney:
    name: Sydney
    display_name: Sydney Smith
    image: sydney.jpg
    email: 
    web: 
    twitter: 
    instagram: 
    description: 
  tara:
    name: Tara
    display_name: Tara Rosenwinkel
    image: tara.jpg
    email: 
    web: 
    twitter: 
    instagram: 
    description: 
  zoe:
    name: Zoe
    display_name: Zoe Swayne
    image: zoe.jpg
    email: 
    web: 
    twitter: 
    instagram: 
    description: 

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

collections:
  items:
    output: true
    permalink: /:collection/:path/
    itemid: true
    itemlabel: true
    contributor: true

stories:
  items:
    output: true
    permalink: /:collection/:path/
    storylabel: true

